language: go
go:
  - 1.4.1
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt54 -y
  - sudo apt-get update -qq
  - sudo apt-get install -yqq libgmp3-dev libreadline6-dev qt54quickcontrols qt54webengine
install:
  - go get code.google.com/p/go.tools/cmd/goimports
  - go get github.com/golang/lint/golint
  # - go get golang.org/x/tools/cmd/vet 
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/mattn/goveralls
  - ETH_DEPS=$(go list -f '{{.Imports}} {{.TestImports}} {{.XTestImports}}' github.com/ethereum/go-ethereum/... | sed -e 's/\[//g' | sed -e 's/\]//g' | sed -e 's/C //g'); if [ "$ETH_DEPS" ]; then go get -d -v $ETH_DEPS; fi
before_script:
  - gofmt -l -w .
  - goimports -l -w .
  - golint .
  # - go vet ./...
  # - go test -race ./...
script:
  - ./gocoverage.sh && if [ "$COVERALLS_TOKEN" ]; then goveralls -coverprofile=profile.cov -service=travis-ci -repotoken $COVERALLS_TOKEN; fi
env:
  global:
    - PKG_CONFIG_PATH=/opt/qt54/lib/pkgconfig
    - LD_LIBRARY_PATH=/opt/qt54/lib
    - secure: "U2U1AmkU4NJBgKR/uUAebQY87cNL0+1JHjnLOmmXwxYYyj5ralWb1aSuSH3qSXiT93qLBmtaUkuv9fberHVqrbAeVlztVdUsKAq7JMQH+M99iFkC9UiRMqHmtjWJ0ok4COD1sRYixxi21wb/JrMe3M1iL4QJVS61iltjHhVdM64="

