# Build Cortex in a stock Go builder container
FROM ubuntu:18.04 as golang-builder

RUN apt-get update && apt-get install -y curl make gcc g++ git python3 cmake

ADD . /CortexTheseus
RUN cd /CortexTheseus && make all

# Pull all binaries into a second stage deploy alpine container
COPY --from=builder /CortexTheseus/build/bin/* /usr/local/bin/

EXPOSE 8545 8546 8547 40404 40404/udp 40401 40401/udp
