# Build Cortex in a stock Go builder container
FROM golang:1.14-alpine as builder

RUN apk add --no-cache make gcc g++ musl-dev linux-headers git

ADD . /CortexTheseus
RUN cd /CortexTheseus && make all

# Pull all binaries into a second stage deploy alpine container
FROM alpine:latest

RUN apk add --no-cache ca-certificates
COPY --from=builder /CortexTheseus/build/bin/* /usr/local/bin/

EXPOSE 8545 8546 8547 40404 40404/udp 40401 40401/udp
