---
- name: update C++ client
  docker_image:
      path: /home/{{ ansible_ssh_user }}/git/ansible/test-files/docker-cppjit
      name: cppjit
      state: build
#  command: docker build -t cpp /home/{{ ansible_ssh_user }}/git/ansible/test-files/docker-cpp
  async: 1200
  poll: 5

- name: update Go client
  docker_image:
      path: /home/{{ ansible_ssh_user }}/git/ansible/test-files/docker-go
      name: go
      state: build
#  command: docker build -t go /home/{{ ansible_ssh_user }}/git/ansible/test-files/docker-go 
  async: 1200
  poll: 5

- name: update Python client
  docker_image:
      path: /home/{{ ansible_ssh_user }}/git/ansible/test-files/docker-python
      name: python
      state: build
  async: 1200
  poll: 5

- name: Run infinite tests 
  shell: seq {{ ansible_processor_vcpus }} | parallel --max-args=0 /home/{{ ansible_ssh_user }}/git/ansible/test-files/testrunner.sh
  # run for two months 
  async: "{{ 60 * 60 * 24 * 30 * 2 }}"
  poll: 0
  register: log_runner

- name: verify previous task
  async_status: jid={{ log_runner.ansible_job_id }}
