---
- name: update C++ client
  sudo: true  
  docker_image:
      path: git/ansible/test-files/docker-cpp
      name: cpp
      state: build

- name: update Go client
  sudo: true 
  docker_image:
      path: git/ansible/test-files/docker-go
      name: go
      state: build

- name: Run infinite tests (press ^C to stop)
  sudo: true
  shell: git/ansible/test-files/testrunner.sh
