// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package torrentfs

import (
	"encoding/json"

	"github.com/ethereum/go-ethereum/common"
)

// MarshalJSON marshals as JSON.
func (f FileInfo) MarshalJSON() ([]byte, error) {
	type FileInfo struct {
		Meta         *FileMeta
		TxHash       *common.Hash
		ContractAddr *common.Address
		LeftSize     uint64
	}
	var enc FileInfo
	enc.Meta = f.Meta
	enc.TxHash = f.TxHash
	enc.ContractAddr = f.ContractAddr
	enc.LeftSize = f.LeftSize
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (f *FileInfo) UnmarshalJSON(input []byte) error {
	type FileInfo struct {
		Meta         *FileMeta
		TxHash       *common.Hash
		ContractAddr *common.Address
		LeftSize     *uint64
	}
	var dec FileInfo
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Meta != nil {
		f.Meta = dec.Meta
	}
	if dec.TxHash != nil {
		f.TxHash = dec.TxHash
	}
	if dec.ContractAddr != nil {
		f.ContractAddr = dec.ContractAddr
	}
	if dec.LeftSize != nil {
		f.LeftSize = *dec.LeftSize
	}
	return nil
}
