// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"

	"github.com/CortexFoundation/CortexTheseus/common"
)

// MarshalJSON marshals as JSON.
func (f FileInfo) MarshalJSON() ([]byte, error) {
	type FileInfo struct {
		TxHash       *common.Hash
		ContractAddr *common.Address
	}
	var enc FileInfo
	enc.TxHash = f.TxHash
	enc.ContractAddr = f.ContractAddr
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (f *FileInfo) UnmarshalJSON(input []byte) error {
	type FileInfo struct {
		TxHash       *common.Hash
		ContractAddr *common.Address
	}
	var dec FileInfo
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.TxHash != nil {
		f.TxHash = dec.TxHash
	}
	if dec.ContractAddr != nil {
		f.ContractAddr = dec.ContractAddr
	}
	return nil
}
