// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"

	"github.com/CortexFoundation/CortexTheseus/common"
)

// MarshalJSON marshals as JSON.
func (r Receipt) MarshalJSON() ([]byte, error) {
	type Receipt struct {
		ContractAddr *common.Address `json:"ContractAddr"`
		TxHash       *common.Hash    `json:"TransactionHash"`
	}
	var enc Receipt
	enc.ContractAddr = r.ContractAddr
	enc.TxHash = r.TxHash
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (r *Receipt) UnmarshalJSON(input []byte) error {
	type Receipt struct {
		ContractAddr *common.Address `json:"ContractAddr"`
		TxHash       *common.Hash    `json:"TransactionHash"`
	}
	var dec Receipt
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.ContractAddr != nil {
		r.ContractAddr = dec.ContractAddr
	}
	if dec.TxHash != nil {
		r.TxHash = dec.TxHash
	}
	return nil
}
