// Code generated by rlpgen. DO NOT EDIT.

package types

import "github.com/CortexFoundation/CortexTheseus/rlp"
import "io"

func (obj *StateAccount) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	w.WriteUint64(obj.Nonce)
	if obj.Balance == nil {
		w.Write(rlp.EmptyString)
	} else {
		if obj.Balance.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.Balance)
	}
	w.WriteBytes(obj.Root[:])
	w.WriteBytes(obj.CodeHash)
	if obj.Upload == nil {
		w.Write(rlp.EmptyString)
	} else {
		if obj.Upload.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.Upload)
	}
	if obj.Num == nil {
		w.Write(rlp.EmptyString)
	} else {
		if obj.Num.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.Num)
	}
	w.ListEnd(_tmp0)
	return w.Flush()
}
