---
# default config for ec2 instances

instance_type:      c4.xlarge  
security_group:     client-tests

# image:              ami-d6e7c084
image:              ami-9eaa1cf6
# region:             ap-southeast-1
region:             us-east-1
keypair:            christoph
# keypair:            client-tests
volume_size_gb:     50

# limit access to AWS to these clients in CDIR notation
ip_access_range:    0.0.0.0/0


project_description: https://github.com/ethereum/tests

total_no_instances: 1
